### ISSUE TITLE
Inconsistent test results after upgrading to 5.3.0 with docker

### ISSUE THREAD

**Issue by NochEinKamel** [garris/BackstopJS#1303]
Somewhat similar to #1298 ...

I'm getting random errors in my tests where the page is rendered in a really weird state.
e.g. when rendering a desktop view the menu is rendered correctly with an input field for the search, but the page content is rendered like it would on a smartphone.

My testcase:

1. change version in package.json
2. rm yarn.lock
3. yarn install
4. yarn run backstop reference --docker --config=x --filter=1page
5. yarn run backstop test --docker --config=x --filter=1page
6. (repeat last step 4 more times)

Results vary depending on backstopjs version:
5.0.7 => All tests succeed
5.1.0 => All tests succeed
5.2.1 => Error: Cannot find module 'puppeteer'
5.3.0 =>
| viewport        | Run 1           | Run 2          | Run 3           | Run 4           | Run 5           |
| ---- | ---- | ---- | ---- | ---- | ---- 
| 400px | ✅ |✅   |✅   |  ✅ |  ✅ |
| 800px |❌ | ❌  | ❌  |  ❌ | ✅ |
| 1024px |❌ | ❌  | ❌  |  ❌ | ❌  |
| 1440px | ✅  | ❌  | ❌  | ✅  | ❌  |

i.e. only smartphone is working

Here is an example of one image generated correctly and another for the same viewport wrong; notice that the right image is also cut off at the bottom; There is a line missing with the copyright notice etc.
![image](https://user-images.githubusercontent.com/379567/115694132-dde6a400-a360-11eb-858b-898fe8b74836.png)

**Comment by gilzow** [comment]
ok, i feel *MUCH* better knowing it isn't just us. And with ours, just like you, we've never seen the phone viewport fail but other viewports seem to fail at random.

**Comment by garris** [comment]
@NochEinKamel @gilzow wow, sorry guys this one is a mystery. 

@gilzow do your tests also run as expected with v5.1.0?  

Looking at the commits -- the only impactful-looking commit was around `mergeImgHack` removal. 

I'll try to take a look for anything else that might have changed and I'll see if I can do something to my tests to repro the issue.

**Comment by gilzow** [comment]
Let me try downgrading and see what happens

**Comment by gilzow** [comment]
well, i'll be. Downgraded to 5.1.0 and none of the scenarios / viewports that were failing in such odd ways are failing now. They all pass. I ran three sets of reference + tests via `--docker` and they all passed.

I'm out of time today but I'll run the tests in my pipelines tomorrow morning  and let you know the results.

**Comment by gilzow** [comment]
ok, running it in the pipelines also produces passing tests! 
For now, I'm downgrading and pinning to v5.1.0. As you look into what might have happened, if you need me to test things, let me know. Happy to do so.

**Comment by garris** [comment]
@NochEinKamel @gilzow   thank you for helping to isolate the issue!   Since I haven't been able to repro it directly myself I may ask you to test a new release candidate to validate that I fixed the bad commit. 

I will try to get to this today (day job and kids at home are major competition for my time) -- I feel bad that the latest release is hosed for a significant segment of users.

Cheers.

**Comment by garris** [comment]
@gilzow @NochEinKamel   I just created a docker repo for this issue.  If either of you get a chance -- please try...
`docker pull garris/github1303:latest`

I reverted any changes between 5.1.0 and 5.3.0 which might be able to create the issue you are seeing.   Let me know if this works as expected.

**Comment by NochEinKamel** [comment]
Thanks for looking into it @garris .
I tried using that image, but only get an error back from docker:

    Error response from daemon: pull access denied for garris/github1303, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Not 100% sure why - shouldn't it be listet on https://hub.docker.com/u/garris?

**Comment by gilzow** [comment]
Ditto. Getting the same error message even after auth'ing to docker.

**Comment by garris** [comment]
Crap 😞.  Let me make sure I made this public.

**Comment by garris** [comment]
Ok, fixed -- it should be public now!

(Sorry, I thought these were defaulted to public)

Please give it another go.   Also, here is the repo I created to troubleshoot the issue...
https://github.com/garris/BackstopJS/tree/github_1303

Here are the steps I've taken:
- I've downgraded puppeteer to 5.5.0.  This _could_ be causing the problem.
- I've reverted a change [here](https://github.com/garris/BackstopJS/commit/29b4f9cda2ba5bd7e70af73e5d9f8feb736db07a) which should not have caused this problem -- but I reverted it anyway just because.

Again -- thanks for bearing with me -- This is a weird problem that I still can't reproduce.

**Comment by gilzow** [comment]
garris/github1303:latest - produces similar results to 5.3.0
I ran the tests with v5.1.0 and with garris/github1303:latest, not changing config or scenarios, viewports, etc. You can see the reports, reference files, test files, etc for both attached.


[garris-github1303.zip](https://file.io/iGw42ZNNMueX)
[backstopjs-v510.zip](https://file.io/BsXcEZqvSaDW)

**Comment by garris** [comment]
@NochEinKamel  Thank you for going the extra mile on getting that docker image configured correctly -- looks like you have isolated the problem.

The good news is that it is not BackstopJS -- it's puppeteer! 🥳
The bad news is that it is not BackstopJS -- it's puppeteer!  😭 
(sorry -- it's the end of the day over here)

I think now the investigation needs to move over to puppeteer.  But to be effective -- we'd want to understand CSS rule or property or combination that consistently causes the issue? I looked at one of @gilzow's results using [diverged](https://github.com/garris/diverged) and found the following problem areas... 
![116167856-0b5f8480-a6b6-11eb-88b4-e6dd19bb990b](https://user-images.githubusercontent.com/447033/116169537-bcb3e980-a6b9-11eb-9f1f-5ca2d6ee6fd0.png)

Also, @gilzow you mentioned that it renders consistently _locally_ -- are you saying when you run docker locally (assuming you're on a mac?) that we don't see this inconsistency issue?   Ideally we'd want to test your CSS in an isolated file and run a simple test multiple times and watch to see the rendering inconsistency.

**Comment by gilzow** [comment]
> Also, @gilzow you mentioned that it renders consistently locally -- are you saying when you run docker locally (assuming you're on a mac?) that we don't see this inconsistency issue?

I have backstopjs installed globally on my mac. If I run the tests against that installation (ie `backstop reference`) then all scenarios+viewports pass. If I then run those same tests with docker, via either `backstop reference --docker` or running them in my gitlab pipeline, the tests fail. 

So I'm guessing the root issue isn't just puppeteer, but puppeteer in combination with docker?

**Comment by NochEinKamel** [comment]
... All I can come up with is an example that doesn't even work on 5.0.7 :-(

```
<style type="text/css">
@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap&subset=cyrillic-ext);
* {
	font-family: Open Sans,"sans serif";
}
</style>
Hello World
```

Works fine without --docker, randomly fails viewports with --docker
Removing the import yields consistent results with --docker

But that's probably a whole different issuee...

**Comment by garris** [comment]
So, font loading?   Is that the issue?  I wonder if the issue is docker or more chromium on Linux? 

Also,  i think there is a font loading event we could listen to  -- in your hello world,  would the problem go away if you waited for a font loaded event?

**Comment by NochEinKamel** [comment]
No, sorry, that's something different.
Adding ```await page.evaluateHandle('document.fonts.ready');``` to the onReady script fixes the hello world above but not my projects testcases.

**Comment by kenny-f** [comment]
> So I'm guessing the root issue isn't just puppeteer, but puppeteer in combination with docker?

I've been seeing the similar problems which seem to point to puppeteer with docker. See https://github.com/garris/BackstopJS/issues/1318#issuecomment-841086680

**Comment by r-oldenburg** [comment]
Same here. Switching from 5.1.0 (docker) to 5.3.4 makes test cases randomly fail. Often caused by a certain "offset" to the left/top. The captured area seems to have the correct size, it is simply the wrong area.

Also it seems that when we are *not* using selectorExpansion it does not seem to happen.

**Comment by arthurbaghdas** [comment]
We are still getting exactly the same issue with the version 6.1.0, anyone has a workaround or fix for this?

**Comment by weseze** [comment]
I'm also getting this issue.
Random failing tests (anywhere from 50-100% are failing), each run fails different scenario's, each run fails in a different way (sometimes the entire document, sometimes only half way down, ...)

The actual difference is always that the screenshots from the test vs. the reference are different height, but both the test and reference should be screenshotting the exact same thing... very weird.

Has anyone found a solution yet?

**Comment by r-oldenburg** [comment]
@weseze and @arthurbaghdas,
actually we were able to mitigate all of these problems. But unfortunately I cannot remember exactly how.

We did a lot of things:

- Added a custom log event when all our JS was loaded and initialized -> waited for it in clickAndHoverHelper
- Added a routine that "waits for all images" and another that "waits for all fonts" in onReady.js (2 times! One in the beginning and another after the clickAndHoverHelper)
- Added further wait/evaluate methods and used them in scenarios (PostInteractionEvent, PostInteractionLogEvent, PostInteractionWait, clickSelectorInterval, scrollToPageEnd)
- Injected CSS on every page that overrides any transition or animation (1)
- In the Backstop-Test-Docker-Image:
   - Skipped the puppeteer browser download (PUPPETEER_SKIP_DOWNLOAD=true npm install backstopjs...)
   - Instead installed the latest chromium-browser (ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium)
- And in Backstop config:
   - Set "engineOptions" -> "headless" to the value "shell" (IMPORTANT for puppeteer to work correctly with latest browser)
   - "engine": "puppeteer"
- There was even a last error that gave me dozens of hours of agony. But I finally tackled it, see (2).
- Also I did introduce a wrapper script which would retry the failed scenario when there was only one single test failing (parsing backstop_data/html_report/config.js)

Oh and we are on BS 6.3.7

Good Luck!

(1) CSS transition override:
```
await page.addStyleTag({content: `
    *, *:before, *:after {
      transition: none !important;
      transition-delay: 0s !important;
      transition-duration: 0s !important;
      animation-delay: 0s !important;
      animation-duration: 0s !important;
      caret-color: transparent !important;
      scroll-behavior:auto !important;
    }
  `});
```

(2) Enforce deterministic drawing of border-radius
```
// enforce composition (dedicated drawing layer) for elements having border-radius
// reason: without this chrome's rendering of these elements is not determinate (sometimes edges are not pixel-perfect identical to reference)
// very probably caused by: https://bugs.chromium.org/p/chromium/issues/detail?id=919955
// approach for workaround: enforce dedicated composite layer by utilizing 'translateZ(0)' which enforces explicit drawing / redrawing
// see https://stackoverflow.com/questions/3485365/how-can-i-force-webkit-to-redraw-repaint-to-propagate-style-changes?page=1&tab=scoredesc#tab-top
// for background infos -> see
//  - https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/
//  - https://www.harrytheo.com/blog/2021/09/dom-reflow-and-layout-thrashing/
//  - https://stackoverflow.com/questions/68852980/why-dont-i-see-layout-reflow-being-triggered-when-changing-and-retrieving-eleme
//  - https://stackoverflow.com/questions/60361968/why-does-reading-dom-measurements-trigger-a-layout-reflow
//  - https://gist.github.com/paulirish/5d52fb081b3570c81e3a
//  - https://stackoverflow.com/questions/21664940/force-browser-to-trigger-reflow-while-changing-css
//  - https://blog.postman.com/ui-repaint-issue-on-chrome/
await page.addStyleTag({content: `
    .enforceComposition {
      transform: translateZ(0);
    }
  `});
  await page.evaluate(async () => {
    try {
      const isInvisible = function(element) {
        return !!element && (getComputedStyle(element)['display'] === 'none' || isInvisible(element.parentElement));
      }
      Array.from(document.querySelectorAll("a, button, i"))
        .filter( x => {
          const computedStyle = getComputedStyle(x);
          return !x.style.transform && computedStyle['transform'] === 'none' && // no transform set
                  !isInvisible(x) &&
                  computedStyle['border-bottom-left-radius'] !== '0px'; // check for non-default value
        })
      .concat(
        Array.from(document.querySelectorAll("img, .teaser__image"))
          .filter( x => {
            return !isInvisible(x) &&
                    getComputedStyle(x)['border-radius'] === '50%';
          }))
      .forEach(x => { x.classList.add('enforceComposition'); });
    } catch (e) {
      console.error(e);
    }
  });
```

**Comment by malcomio** [comment]
Thanks @r-oldenburg - removing the animations (and in our case opacity for some initially off-screen elements) helped us reduce the number of false positives
